apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: skybooker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:11
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: global-config
            - secretRef:
                name: skybooker-secrets
          volumeMounts:
            - name: logs
              mountPath: /app/logs
      volumes:
        - name: logs
          hostPath:
            path: /app/logs
            type: DirectoryOrCreate
