apiVersion: apps/v1
kind: Deployment
metadata:
  name: messagingservice
  namespace: skybooker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messagingservice
  template:
    metadata:
      labels:
        app: messagingservice
    spec:
      containers:
        - name: messagingservice
          image: nelonissle7/kub_messaging:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: flight-config
            - configMapRef:
                name: global-config
            - secretRef:
                name: skybooker-secrets
          volumeMounts:
            - name: logs
              mountPath: /app/logs
      volumes:
        - name: logs
          hostPath:
            path: /app/logs
            type: DirectoryOrCreate
