filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /app/logs/*.log   
  multiline.pattern: '^\d{4}-\d{2}-\d{2}'
  multiline.negate: true
  multiline.match: after

setup.template.name: "filebeat"
setup.template.pattern: "filebeat-*"
setup.template.overwrite: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: "elastic"      
  password: "NXJF=OWN8UmlzuNs5p05"      
  index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"
