# SkyBooker AuthService Dockerfile
# run docker build -t authservice-migration:latest -f Dockerfile-migration .

# Migration stage
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore "AuthService.csproj"
RUN dotnet publish "AuthService.csproj" -c Release -o /app/publish
RUN dotnet tool install --global dotnet-ef
ENV PATH="$PATH:/root/.dotnet/tools"

VOLUME ["/app/logs"]
VOLUME ["/app/data"]
ENTRYPOINT ["dotnet", "ef", "database", "update"]
