apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: skybooker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
          envFrom:
           - configMapRef:
               name: elastic-config
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: logs
              mountPath: /app/logs
      volumes:
        - name: logs
          hostPath:
            path: /app/logs
            type: DirectoryOrCreate
