apiVersion: apps/v1
kind: Deployment
metadata:
  name: promtail
  namespace: skybooker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      containers:
        - name: promtail
          image: grafana/promtail:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: logs
              mountPath: /app/logs
      volumes:
        - name: logs
          hostPath:
            path: /app/logs
            type: DirectoryOrCreate
