apiVersion: v1
kind: Secret
metadata:
  name: skybooker-secrets
  namespace: skybooker
type: Opaque
stringData:
  JwtSettings__Key: {{ .Values.secrets.JwtSettings__Key | quote }}

  TWILIO_ACCOUNTSID:  {{ .Values.secrets.TWILIO_ACCOUNTSID | quote }}
  TWILIO_AUTHTOKEN: {{ .Values.secrets.TWILIO_AUTHTOKEN | quote }}
  TWILIO_PHONE_NUMBER: {{ .Values.secrets.TWILIO_PHONE_NUMBER | quote }}
  MESSAGING_DESTINATIONPHONE: {{ .Values.secrets.MESSAGING_DESTINATIONPHONE | quote }}

  SA_PASSWORD: {{ .Values.secrets.SA_PASSWORD | quote }}
  ConnectionStrings__SqlServer: {{ .Values.secrets.ConnectionStrings__SqlServer | quote }}

  MONGO_PASSWORD: {{ .Values.secrets.MONGO_PASSWORD | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.secrets.MONGO_INITDB_ROOT_PASSWORD | quote }}
  ConnectionStrings__MongoDb: {{ .Values.secrets.ConnectionStrings__MongoDb | quote }}

  RABBITMQ_DEFAULT_PASS: {{ .Values.secrets.RABBITMQ_DEFAULT_PASS | quote }}

  GRAFANA_ADMIN_PASSWORD: {{ .Values.secrets.GRAFANA_ADMIN_PASSWORD | quote }}
