secrets:
  JWTROOTTOKEN: "$JWTROOTTOKEN"
  AUTH_ADMIN_PWD: "$AUTH_ADMIN_PWD"

  MARIADB_PASSWORD: "$MARIADB_PASSWORD"
  MARIADB_ROOT_PASSWORD: "$MARIADB_ROOT_PASSWORD"

  MONGO_PASSWORD: "$MONGO_PASSWORD"
  MONGO_INITDB_ROOT_PASSWORD: "$MONGO_INITDB_ROOT_PASSWORD"
  MONGO_INITDB_ROOT_USERNAME: "$MONGO_INITDB_ROOT_USERNAME"
  MONGO_DATABASE_NAME: "$MONGO_DATABASE_NAME"

  TWILIO_ACCOUNTSID: "$TWILIO_ACCOUNTSID"
  TWILIO_AUTHTOKEN: "$TWILIO_AUTHTOKEN"
  TWILIO_PHONE_NUMBER: "$TWILIO_PHONE_NUMBER"
  MESSAGING_DESTINATIONPHONE: "$MESSAGING_DESTINATIONPHONE"

  RABBITMQ_DEFAULT_PASS: "$RABBITMQ_DEFAULT_PASS"

  GRAFANA_ADMIN_PASSWORD: "$GRAFANA_ADMIN_PASSWORD"
  GF_SECURITY_ADMIN_PASSWORD: "$GF_SECURITY_ADMIN_PASSWORD"





  

