# SkyBooker BookingService Dockerfile
# run docker build -t bookingservice-migration:latest -f Dockerfile-migration .

# Migration stage
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY . .
RUN dotnet tool install --global dotnet-ef
ENV PATH="$PATH:/root/.dotnet/tools"
RUN dotnet restore "BookingService.csproj"
RUN dotnet publish "BookingService.csproj" -c Release -o /app/publish

VOLUME ["/app/logs"]
ENTRYPOINT ["dotnet", "ef", "database", "update"]
