apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookingservice
  namespace: skybooker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookingservice
  template:
    metadata:
      labels:
        app: bookingservice
    spec:
      containers:
        - name: bookingservice
          image: nelonissle7/kub_booking:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: booking-config
            - configMapRef:
                name: global-config
            - secretRef:
                name: skybooker-secrets
          volumeMounts:
            - name: logs
              mountPath: /app/logs
      volumes:
        - name: logs
          hostPath:
            path: /app/logs
            type: DirectoryOrCreate
