apiVersion: v1
kind: Service
metadata:
  name: bookingservice-migration
  namespace: skybooker
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: bookingservice-migration
